# Configuration for the documentation hosted via Github pages
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: RDP MQTT Client
description: The MQTT Client library provides MQTT functionality for the RDP, supporting multiple payload formats including JSON, compressed JSON with ZSTD, and SparkplugB protocol.
show_downloads: true
